[bot]
name = "DisSkele"                       # Your bot name
status = "online"                       # The status of the bot; online, idle, etc...
activity = "DisSkele - A d.py skeleton" # The activity message
prefix = ".ds"                          # Not used but required by discord.py

[ids]
sudo_users = [
    1027380375028244551, # roc.py
]
home_guild = 1260647611677806633 # R&D - used for errors and emojis

[colors]
primary = 0xFFFFFF   # Used as the primary embed color
secondary = 0x868686 # Used for embed separation
invisible = 0x2B2D31 # Invisible embed color (dark mode only)
success = 0x00D355   # Used on command success
error = 0xDF0043     # Used on command errors

[emojis]
arrow_right = "<:arrow_right:1260669225853255796>"
chat = "<:chat:1260669237693907005>"
dns = "<:dns:1260669235311546502>"
false = "<:false:1260669233986273431>"
ping = "<:ping:1260669232312619068>"
trend_up = "<:trend_up:1260669239677816922>"
true = "<:true:1260669236343341208>"
